package com.chengguan.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.chengguan.dao.checkcontent;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "CHECKCONTENT".
 */
public class checkcontentDao extends AbstractDao<checkcontent, Long> {

    public static final String TABLENAME = "CHECKCONTENT";

    /**
     * Properties of entity checkcontent.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Standardid = new Property(1, Integer.class, "standardid", false, "STANDARDID");
        public final static Property Standard = new Property(2, String.class, "standard", false, "STANDARD");
        public final static Property Point = new Property(3, String.class, "point", false, "POINT");
        public final static Property Classifyid = new Property(4, Integer.class, "classifyid", false, "CLASSIFYID");
    }

    ;


    public checkcontentDao(DaoConfig config) {
        super(config);
    }

    public checkcontentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "\"CHECKCONTENT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"STANDARDID\" INTEGER," + // 1: standardid
                "\"STANDARD\" TEXT," + // 2: standard
                "\"POINT\" TEXT," + // 3: point
                "\"CLASSIFYID\" INTEGER);"); // 4: classifyid
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CHECKCONTENT\"";
        db.execSQL(sql);
    }

    /**
     * @inheritdoc
     */
    @Override
    protected void bindValues(SQLiteStatement stmt, checkcontent entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        Integer standardid = entity.getStandardid();
        if (standardid != null) {
            stmt.bindLong(2, standardid);
        }

        String standard = entity.getStandard();
        if (standard != null) {
            stmt.bindString(3, standard);
        }

        String point = entity.getPoint();
        if (point != null) {
            stmt.bindString(4, point);
        }

        Integer classifyid = entity.getClassifyid();
        if (classifyid != null) {
            stmt.bindLong(5, classifyid);
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    /**
     * @inheritdoc
     */
    @Override
    public checkcontent readEntity(Cursor cursor, int offset) {
        checkcontent entity = new checkcontent( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
                cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // standardid
                cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // standard
                cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // point
                cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4) // classifyid
        );
        return entity;
    }

    /**
     * @inheritdoc
     */
    @Override
    public void readEntity(Cursor cursor, checkcontent entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setStandardid(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setStandard(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPoint(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setClassifyid(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
    }

    /**
     * @inheritdoc
     */
    @Override
    protected Long updateKeyAfterInsert(checkcontent entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long getKey(checkcontent entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

}
