package com.chengguan.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.chengguan.dao.checkclassify;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "CHECKCLASSIFY".
 */
public class checkclassifyDao extends AbstractDao<checkclassify, Long> {

    public static final String TABLENAME = "CHECKCLASSIFY";

    /**
     * Properties of entity checkclassify.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Classifyid = new Property(1, Integer.class, "classifyid", false, "CLASSIFYID");
        public final static Property Classifyname = new Property(2, String.class, "classifyname", false, "CLASSIFYNAME");
    }

    ;


    public checkclassifyDao(DaoConfig config) {
        super(config);
    }

    public checkclassifyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "\"CHECKCLASSIFY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CLASSIFYID\" INTEGER," + // 1: classifyid
                "\"CLASSIFYNAME\" TEXT);"); // 2: classifyname
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CHECKCLASSIFY\"";
        db.execSQL(sql);
    }

    /**
     * @inheritdoc
     */
    @Override
    protected void bindValues(SQLiteStatement stmt, checkclassify entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        Integer classifyid = entity.getClassifyid();
        if (classifyid != null) {
            stmt.bindLong(2, classifyid);
        }

        String classifyname = entity.getClassifyname();
        if (classifyname != null) {
            stmt.bindString(3, classifyname);
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    /**
     * @inheritdoc
     */
    @Override
    public checkclassify readEntity(Cursor cursor, int offset) {
        checkclassify entity = new checkclassify( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
                cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // classifyid
                cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // classifyname
        );
        return entity;
    }

    /**
     * @inheritdoc
     */
    @Override
    public void readEntity(Cursor cursor, checkclassify entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setClassifyid(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setClassifyname(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
    }

    /**
     * @inheritdoc
     */
    @Override
    protected Long updateKeyAfterInsert(checkclassify entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long getKey(checkclassify entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

}
