package com.chengguan.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "CHECKCONTENT".
 */
public class checkcontent {

    private Long id;
    private Integer standardid;
    private String standard;
    private String point;
    private Integer classifyid;

    public checkcontent() {
    }

    public checkcontent(Long id) {
        this.id = id;
    }

    public checkcontent(Long id, Integer standardid, String standard, String point, Integer classifyid) {
        this.id = id;
        this.standardid = standardid;
        this.standard = standard;
        this.point = point;
        this.classifyid = classifyid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getStandardid() {
        return standardid;
    }

    public void setStandardid(Integer standardid) {
        this.standardid = standardid;
    }

    public String getStandard() {
        return standard;
    }

    public void setStandard(String standard) {
        this.standard = standard;
    }

    public String getPoint() {
        return point;
    }

    public void setPoint(String point) {
        this.point = point;
    }

    public Integer getClassifyid() {
        return classifyid;
    }

    public void setClassifyid(Integer classifyid) {
        this.classifyid = classifyid;
    }

}
