package com.chengguan.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "CHECKCLASSIFY".
 */
public class checkclassify {

    private Long id;
    private Integer classifyid;
    private String classifyname;

    public checkclassify() {
    }

    public checkclassify(Long id) {
        this.id = id;
    }

    public checkclassify(Long id, Integer classifyid, String classifyname) {
        this.id = id;
        this.classifyid = classifyid;
        this.classifyname = classifyname;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getClassifyid() {
        return classifyid;
    }

    public void setClassifyid(Integer classifyid) {
        this.classifyid = classifyid;
    }

    public String getClassifyname() {
        return classifyname;
    }

    public void setClassifyname(String classifyname) {
        this.classifyname = classifyname;
    }

}
