package com.chengguan.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.chengguan.dao.checkclassify;
import com.chengguan.dao.checkcontent;

import com.chengguan.dao.checkclassifyDao;
import com.chengguan.dao.checkcontentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig checkclassifyDaoConfig;
    private final DaoConfig checkcontentDaoConfig;

    private final checkclassifyDao checkclassifyDao;
    private final checkcontentDao checkcontentDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        checkclassifyDaoConfig = daoConfigMap.get(checkclassifyDao.class).clone();
        checkclassifyDaoConfig.initIdentityScope(type);

        checkcontentDaoConfig = daoConfigMap.get(checkcontentDao.class).clone();
        checkcontentDaoConfig.initIdentityScope(type);

        checkclassifyDao = new checkclassifyDao(checkclassifyDaoConfig, this);
        checkcontentDao = new checkcontentDao(checkcontentDaoConfig, this);

        registerDao(checkclassify.class, checkclassifyDao);
        registerDao(checkcontent.class, checkcontentDao);
    }

    public void clear() {
        checkclassifyDaoConfig.getIdentityScope().clear();
        checkcontentDaoConfig.getIdentityScope().clear();
    }

    public checkclassifyDao getCheckclassifyDao() {
        return checkclassifyDao;
    }

    public checkcontentDao getCheckcontentDao() {
        return checkcontentDao;
    }

}
